# Artificial Neural Network

### Import Data Sets And Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

In [2]:
data_set = pd.read_csv('Churn_Modelling.csv')
data_set.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
X = data_set.iloc[:, 3:13].values
y = data_set.iloc[:, -1].values
print(X, y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]] [1 0 1 ... 1 1 0]


### Taking Care of Catagorical Data

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [5]:
# for geographical location
LabelEncoder_Geography = LabelEncoder()
X[:, 1] = LabelEncoder_Geography.fit_transform(X[:, 1])

In [6]:
X[:, 1],
print(X)

[[619 0 'Female' ... 1 1 101348.88]
 [608 2 'Female' ... 0 1 112542.58]
 [502 0 'Female' ... 1 0 113931.57]
 ...
 [709 0 'Female' ... 0 1 42085.58]
 [772 1 'Male' ... 1 0 92888.52]
 [792 0 'Female' ... 1 0 38190.78]]


In [7]:
# for gender
LabelEncoder_Geography = LabelEncoder()
X[:, 2] = LabelEncoder_Geography.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]


In [9]:
one_hot_encoder = OneHotEncoder()
X = one_hot_encoder.fit_transform(X).toarray()

In [10]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
X = X[:, 1:]

In [12]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### Spliting Data Sets Into Training And Testing Sets

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
print(X_train, X_test, y_train, y_test)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] [0 1 0 ... 1 0 0] [1 0 0 ... 0 0 0]


### Building ANN

In [15]:
# Initializing ANN
classifier = tf.keras.models.Sequential()

In [16]:
#Adding Input Layer
classifier.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [17]:
#Adding Input Layer
classifier.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [18]:
#Adding Input Layer
classifier.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [19]:
classifier.compile(optimizer = 'adam',
                  loss = 'binary_crossentropy',
                  metrics = ["accuracy"])

In [20]:
classifier.fit(X_train, y_train, batch_size = 32, epochs = 100, verbose = 1)

Epoch 1/100
250/250 [==============================] - 1s 5ms/step - loss: 0.5033 - accuracy: 0.8002
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3448 - accuracy: 0.8601
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 0.2683 - accuracy: 0.8975
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 0.1969 - accuracy: 0.9311
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 0.1240 - accuracy: 0.9659
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.0674 - accuracy: 0.9870
Epoch 7/100
250/250 [==============================] - 2s 7ms/step - loss: 0.0348 - accuracy: 0.9960
Epoch 8/100
250/250 [==============================] - 1s 6ms/step - loss: 0.0189 - accuracy: 0.9989
Epoch 9/100
250/250 [==============================] - 2s 6ms/step - loss: 0.0111 - accuracy: 0.9995
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.0070 - accura

250/250 [==============================] - 1s 5ms/step - loss: 3.2008e-08 - accuracy: 1.0000
Epoch 79/100
250/250 [==============================] - 1s 5ms/step - loss: 2.8417e-08 - accuracy: 1.0000
Epoch 80/100
250/250 [==============================] - 1s 5ms/step - loss: 2.5336e-08 - accuracy: 1.0000
Epoch 81/100
250/250 [==============================] - 1s 5ms/step - loss: 2.2580e-08 - accuracy: 1.0000
Epoch 82/100
250/250 [==============================] - 1s 5ms/step - loss: 2.0154e-08 - accuracy: 1.0000
Epoch 83/100
250/250 [==============================] - 1s 5ms/step - loss: 1.8063e-08 - accuracy: 1.0000
Epoch 84/100
250/250 [==============================] - 1s 5ms/step - loss: 1.6206e-08 - accuracy: 1.0000
Epoch 85/100
250/250 [==============================] - 1s 5ms/step - loss: 1.4607e-08 - accuracy: 1.0000
Epoch 86/100
250/250 [==============================] - 1s 5ms/step - loss: 1.3175e-08 - accuracy: 1.0000
Epoch 87/100
250/250 [==============================] - 1s 

### Predicting Results

In [21]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

### Confussion Matrix

In [22]:
from sklearn.metrics import confusion_matrix

In [23]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1349  245]
 [ 198  208]]


# END